#ifndef GSVIRTUALMACHINE_GS_STATEMENTTYPES_H
#define GSVIRTUALMACHINE_GS_STATEMENTTYPES_H

namespace GSVirtualMachine::Statements {

    enum class StatementType {
        PUSH_STATEMENT,
        POP_STATEMENT,

        ADD_STATEMENT,
        SUB_STATEMENT,

        LT_STATEMENT,

        GET_STATEMENT,
        SAVE_STATEMENT,
        RESERVE_STATEMENT,

        JZ_STATEMENT,
        JNZ_STATEMENT,
        JMP_STATEMENT
    };

}

#endif //GSVIRTUALMACHINE_GS_STATEMENTTYPES_H
